2020-08-26T04:09:54.6268637+08:00|1|INFO|DataSync.Log|Storage folder: C:\Users\jackh\Desktop\cook\Assets\TestData\TestStore successfully validated. 
2020-08-26T04:09:54.6577822+08:00|12|INFO|DataSync.Log|StorageSize. StorageSize: 0. 
2020-08-26T04:09:54.7146005+08:00|12|INFO|DataSync.Log|MovedFromStorageToSender. 
2020-08-26T04:09:54.7670857+08:00|12|INFO|DataSync.Log|MovedFromStorageToBuffer. 
2020-08-26T04:09:54.8199450+08:00|12|INFO|DataSync.Log|MovedFromBufferToSender. 
2020-08-26T04:10:24.6747186+08:00|9|INFO|DataSync.Log|SerializationStarted. Items count: 1 
2020-08-26T04:10:24.9310329+08:00|9|INFO|DataSync.Log|TransmitterEnqueue. TransmissionId: ebedaf1bbef94601abfeb23767df6e77(0-0). 
2020-08-26T04:10:24.9310329+08:00|9|INFO|DataSync.Log|TransmissionSendStarted. TransmissionId: ebedaf1bbef94601abfeb23767df6e77(0-0). 
2020-08-26T04:10:46.2627140+08:00|69|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: ebedaf1bbef94601abfeb23767df6e77(0-0). Message: System.Net.WebException: Error: ConnectFailure (連線嘗試失敗，因為連線對象有一段時間並未正確回應，或是連線建立失敗，因為連線的主機無法回應。 ) ---> System.Net.Sockets.SocketException: 連線嘗試失敗，因為連線對象有一段時間並未正確回應，或是連線建立失敗，因為連線的主機無法回應。    at System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP) [0x000b6] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Net.WebConnection.Connect (System.Net.HttpWebRequest request) [0x0016d] in <735c83e43c004ee998f77c68cf8035da>:0     --- End of inner exception stack trace ---   at System.Net.HttpWebRequest.EndGetRequestStream (System.IAsyncResult asyncResult) [0x0003a] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x0000f] in <599589bf4ce248909b8a14cbe4a2034e>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<GetResponseAsync>d__39.MoveNext () [0x00086] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<SendAsync>d__36.MoveNext () [0x0017d] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.TransmissionSender+<StartSending>d__24.MoveNext () [0x000bb] in <20f93252061247f09e8451bed298b761>:0 . 
2020-08-26T04:10:46.2667053+08:00|69|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: ebedaf1bbef94601abfeb23767df6e77(0-0). Message: Error: ConnectFailure (連線嘗試失敗，因為連線對象有一段時間並未正確回應，或是連線建立失敗，因為連線的主機無法回應。 ). StatusCode: 0. Description: . 
